from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Python Dialog")
        Dialog.resize(1600, 900)
        self.groupBox1 = QtWidgets.QGroupBox(Dialog)
        self.groupBox1.setGeometry(QtCore.QRect(0, 0, 800, 900))
        self.groupBox2 = QtWidgets.QGroupBox(Dialog)
        self.groupBox2.setGeometry(QtCore.QRect(800, 0, 800, 900))
        #self.groupBox.setObjectName("groupBox")
        self.textEdit = QtWidgets.QTextEdit(self.groupBox1)
        self.textEdit.setGeometry(QtCore.QRect(20, 50, 500, 30))
        #self.textEdit.setObjectName("textEdit")
        self.comboBox1 = QtWidgets.QComboBox(self.groupBox1)
        self.comboBox1.setGeometry(QtCore.QRect(200, 20, 91, 20))
        #self.comboBox.setObjectName("comboBox")
        self.comboBox1.addItem("")
        self.comboBox1.addItem("")
        self.comboBox1.addItem("")
        self.comboBox2 = QtWidgets.QComboBox(self.groupBox1)
        self.comboBox2.setGeometry(QtCore.QRect(600, 20, 91, 20))
        self.comboBox2.addItem("")
        self.comboBox2.addItem("")
        self.comboBox2.addItem("")
        self.comboBox2.addItem("")
        self.comboBox2.addItem("")
        self.label1 = QtWidgets.QLabel(self.groupBox1)
        self.label1.setGeometry(QtCore.QRect(30, 20, 100, 21))
        self.label2 = QtWidgets.QLabel(self.groupBox1)
        self.label2.setGeometry(QtCore.QRect(430, 20, 100, 21))
        #self.label.setObjectName("label")
        self.queryBtn = QtWidgets.QPushButton(Dialog)
        self.queryBtn.setGeometry(QtCore.QRect(40, 100, 75, 23))
        self.queryBtn.setMaximumSize(QtCore.QSize(75, 16777215))
        #self.queryBtn.setObjectName("queryBtn")
        self.clearBtn = QtWidgets.QPushButton(Dialog)
        self.clearBtn.setGeometry(QtCore.QRect(250, 100, 75, 23))
        self.clearBtn.setMaximumSize(QtCore.QSize(75, 16777215))
        #self.clearBtn.setObjectName("clearBtn")
        self.retranslateUi(Dialog)
        self.queryBtn.clicked.connect(Dialog.queryArticle)
        self.clearBtn.clicked.connect(Dialog.clearText)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.groupBox1.setTitle(_translate("Dialog", "Category And Search"))
        self.comboBox1.setItemText(0, _translate("Dialog", "Article"))
        self.comboBox1.setItemText(1, _translate("Dialog", "Skill"))
        self.comboBox1.setItemText(2, _translate("Dialog", "Girl"))
        self.label1.setText(_translate("Dialog", "Category 1"))
        self.comboBox2.setItemText(0, _translate("Dialog", "Android"))
        self.comboBox2.setItemText(1, _translate("Dialog", "iOS"))
        self.comboBox2.setItemText(2, _translate("Dialog", "Flutter"))
        self.comboBox2.setItemText(3, _translate("Dialog", "Frontend"))
        self.comboBox2.setItemText(4, _translate("Dialog", "App"))
        self.label2.setText(_translate("Dialog", "Category 2"))
        self.queryBtn.setText(_translate("Dialog", "Search"))
        self.clearBtn.setText(_translate("Dialog", "Clear"))
        self.groupBox2.setTitle(_translate("Dialog", "Detials"))